project:
  type: website
  output-dir: _site

website:
  title: "Autorenvita Sebastian Sukstorf"
  navbar:
    # Social-Icons rechts (optional)
    right:
      - icon: instagram
        href: https://www.instagram.com/sukstorfsebastian/
      - icon: youtube
        href: https://www.youtube.com/@SSukstorf
    background: "#24376F"     # <— hier deinen Farbwert einsetzen, z. B. "#6E8C7A"
    foreground: "#ffffff"        # weiße Schrift auf der Navbar (Kontrast)

format:
  html:
    embed-resources: true
