project:
  type: website
  output-dir: _site
  resources:
    - lesungen.csv
    - sebastian.jpg
    - icons/*

website:
  #title: "Autorenvita Sebastian Sukstorf"
  navbar: false
  search: false
  page-navigation: false

format:
  html:
    embed-resources: true
    toc: false
    lang: de
    link-external-newwindow: true
